[package]
name = "sbus-rcv"
version = "0.1.0"
edition = "2024"

[dependencies]
sbus-rs = { path = "../sbus-rs", features = ["blocking"] }
embassy-executor = { version = "0.7.0", git = "https://github.com/embassy-rs/embassy.git", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { version = "0.4.0",     git = "https://github.com/embassy-rs/embassy.git", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { version = "0.4.0", git = "https://github.com/embassy-rs/embassy.git", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl", "rp235xa"] }
embassy-futures = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy.git" }
defmt = "1.0.1"
defmt-rtt = "1.0.0"
cortex-m-rt = "0.7.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }

[profile.release]
debug = 2

[lib]
test = false
bench = false

[[bin]]
name = "printer"
test = false
bench = false

[[bin]]
name = "eagle"
test = false
bench = false
