[package]
name = "elle-rpc-icd"
version.workspace = true
edition.workspace = true
description = "Interface Control Document for Elle RPC protocol"

[features]
default = []
use-std = ["postcard/use-std", "postcard-rpc/use-std", "postcard-schema/use-std", "serde/std"]

[dependencies]
postcard = { workspace = true }
postcard-rpc = { workspace = true }
postcard-schema = { workspace = true }
serde = { workspace = true }
heapless = { workspace = true }

[lib]
test = false
bench = false
